services:
  intranet-prod:
    container_name: intranet-prod
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rconetwork"
      - "traefik.http.routers.intranet.rule=Host(`intranet-prod.rose-croix-d-or.org`) && PathPrefix(`/`)"
      - "traefik.http.routers.intranet.entrypoints=websecure"