services:
  intranet:
    image: ghcr.io/almyfad/intranet:latest
    environment:
      - API_URL=api.url
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rconetwork"
      - "traefik.http.routers.intranet.rule=Host(`intranet-dev.rose-croix-d-or.org`) && PathPrefix(`/`)"
      - "traefik.http.routers.intranet.entrypoints=websecure"
      - "traefik.http.routers.intranet.tls.certresolver=myresolver"

    networks:
      - rconetwork
networks:
  rconetwork:
    external: true