volumes:
  traefik_letsencrypt:
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true" # Interface web de Traefik (désactiver en production si non nécessaire)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=guadeloupe@rose-croix-d-or.org" # Remplacez par votre email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Nécessaire pour que Traefik détecte les conteneurs Docker
      - traefik_letsencrypt:/letsencrypt
    restart: always
    networks:
      - rconetwork
networks:
  rconetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
