services:
  helios:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    labels:
      - "traefik.http.routers.helios.rule=Host(`helios-staging.rose-croix-d-or.org`)"
    networks:
      rconetwork:
networks:
  rconetwork:
    external: true