services:
  helios:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    labels: 
      - "traefik.http.routers.helios.rule=Host(`helios.rose-croix-d-or.org`)"
    networks:
      rconetwork:
    secrets:
      - mysql_password
      - jwt_secret
networks:
  rconetwork:
    external: true
secrets:
  mysql_password:
    external: true
    name: $HOME/helios/.secret.helios.prod.mysql.password
  jwt_secret:
    external: true
    name: $HOME/helios/.secret.helios.prod.jwt.secret