services:
  helios:
    container_name: helios-staging
    labels:
      - "traefik.http.routers.helios.rule=Host(`helios-staging.rose-croix-d-or.org`)"
    networks:
      rconetwork:
    secrets:
      - mysql_password
      - jwt_secret
networks:
  rconetwork:
    external: true
secrets:
  mysql_password:
    file: .secret.helios.staging.mysql.password
  jwt_secret:
    file: .secret.helios.staging.jwt.secret