services:
  helios-staging:
    container_name: helios-staging
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    labels:
      - "traefik.http.routers.helios.rule=Host(`helios-staging.rose-croix-d-or.org`)"
    networks:
      rconetwork:
    secrets:
      - mysql_password
      - jwt_secret
networks:
  rconetwork:
    external: true
secrets:
  mysql_password:
    file: $HOME/helios/.secret.helios.staging.mysql.password
  jwt_secret:
    file: $HOME/helios/.secret.helios.staging.jwt.secret