services:
  helios:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    labels: 
      - "traefik.http.routers.helios.rule=Host(`helios.rose-croix-d-or.org`)"
    networks:
      rconetwork:
networks:
  rconetwork:
    external: true