services:
  helios:
    labels:
      traefik.http.routers.helios.rule: Host(`helios-dev.rose-croix-d-or.org`)
    networks:
      rconetwork:
    secrets:
      - mysql_password
      - jwt_secret
networks:
  rconetwork:
    external: true
secrets:
  mysql_password:
    file: .secret.helios.dev.mysql.password
  jwt_secret:
    file: .secret.helios.dev.jwt.secret