@helios_HostAddress = http://localhost:5229
@keycloak_HostAddress = http://localhost:8080
@realm = rco
@client_id = intranet
@username = lsene
@password = Azerty00!

# @name getToken
POST {{keycloak_HostAddress}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&username={{username}}&password={{password}}&scope=openid%20profile%20email

###

# @name logout
POST {{keycloak_HostAddress}}/realms/{{realm}}/protocol/openid-connect/logout
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&refresh_token={{getToken.response.body.$.refresh_token}}

###

GET {{helios_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{helios_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{getToken.response.body.$.access_token}}

###
