/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeActiviteDTO } from './typeActiviteDTO';
import { CentreDTO2 } from './centreDTO2';
import { ProgrammeDTO } from './programmeDTO';


export interface ActivityDTO { 
    id: number;
    libelle: string;
    debut: string;
    fin: string;
    typeActivite: TypeActiviteDTO;
    programme: ProgrammeDTO | null;
    centre: CentreDTO2 | null;
    description: string | null;
}

