/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgrammeDTO2 } from './programmeDTO2';


export interface CentreProgrammeDTO { 
    id: number | null;
    libelle: string | null;
    programmes: Array<ProgrammeDTO2> | null;
}

