/**
 * Helios | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NullableOfCivilites } from './nullableOfCivilites';


export interface CiviliteDTO { 
    id: number | null;
    libelle: string | null;
    code: NullableOfCivilites | null;
}
export namespace CiviliteDTO {
}


