/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateActivityDTO { 
    libelle: string;
    description: string | null;
    dateDebut: string;
    dateFin: string;
    isAllDay: boolean;
    typeActiviteeId: number;
    centreId: number;
    programmeId: number;
}

