/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FlatProgrammeDTO { 
    id: number;
    libelle: string;
    description: string | null;
    couleur: string | null;
    centreId: number | null;
    centreLibelle: string | null;
}

