/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Modules = {
    SysAdmin: 'SysAdmin',
    Accueil: 'Accueil',
    Conferences: 'Conferences',
    ConferencesInscriptions: 'ConferencesInscriptions',
    ConferencesUserInscriptions: 'ConferencesUserInscriptions',
    Registre: 'Registre',
    RegistreFicheEleves: 'RegistreFicheEleves',
    RegistreFicheParvis: 'RegistreFicheParvis',
    RegistreFicheContacts: 'RegistreFicheContacts',
    RegistreFicheJeunesses: 'RegistreFicheJeunesses',
    RegistreFicheJeunesRosicruciens: 'RegistreFicheJeunesRosicruciens',
    RegistreSaisiePresences: 'RegistreSaisiePresences',
    RegistreSaisiePresencesVilles: 'RegistreSaisiePresencesVilles',
    RegistreSaisiePresencesCr: 'RegistreSaisiePresencesCR',
    RegistreSaisiePresencesEi: 'RegistreSaisiePresencesEI',
    RegistreStatistiques: 'RegistreStatistiques',
    RegistreStatistiquesPresences: 'RegistreStatistiquesPresences',
    RegistreStatistiquesMouvements: 'RegistreStatistiquesMouvements',
    Comptabilite: 'Comptabilite',
    ComptabiliteEnLigne: 'ComptabiliteEnLigne',
    ComptabiliteParametres: 'ComptabiliteParametres',
    ComptabiliteSaisieEcrituresRepetitives: 'ComptabiliteSaisieEcrituresRepetitives',
    ComptabiliteComptesCaisse: 'ComptabiliteComptesCaisse',
    Administation: 'Administation',
    Mailing: 'Mailing',
    MailingListes: 'MailingListes',
    MailingCampagnes: 'MailingCampagnes',
    Planning: 'Planning',
    Developpement: 'Developpement',
    Logout: 'Logout'
} as const;
export type Modules = typeof Modules[keyof typeof Modules];

