/**
 * Helios | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NullableOfCivilites = {
    Monsieur: 'Monsieur',
    Madame: 'Madame'
} as const;
export type NullableOfCivilites = typeof NullableOfCivilites[keyof typeof NullableOfCivilites];

