/**
 * Helios | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const NullableOfTypesMembres = {
    PremierAspect: 'PremierAspect',
    DeuxiemeAspect: 'DeuxiemeAspect',
    Ecs: 'ECS',
    Ecclesia: 'ECCLESIA',
    Graal: 'GRAAL',
    CinquiemeAspect: 'CinquiemeAspect',
    SixiemeAspect: 'SixiemeAspect',
    SeptiemeAspect: 'SeptiemeAspect',
    Interesse: 'Interesse',
    Contact: 'Contact',
    Jeunesse: 'Jeunesse',
    EnfantGroupePreA: 'EnfantGroupePreA',
    EnfantGroupeA: 'EnfantGroupeA',
    EnfantGroupeB: 'EnfantGroupeB',
    EnfantGroupeC: 'EnfantGroupeC',
    EnfantGroupeD: 'EnfantGroupeD',
    EnfantHorsGroupe: 'EnfantHorsGroupe',
    GroupeD: 'GroupeD',
    GroupeDPlus: 'GroupeDPlus'
} as const;
export type NullableOfTypesMembres = typeof NullableOfTypesMembres[keyof typeof NullableOfTypesMembres];

