/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CentreDTO } from './centreDTO';


export interface ProgrammeDTO2 { 
    id: number;
    libelle: string;
    description: string | null;
    centres: Array<CentreDTO> | null;
}

