/**
 * Helios | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TimelineMembreTypes = {
    PremierContact: 'PremierContact',
    Bapteme: 'Bapteme',
    MariageBenediction: 'MariageBenediction',
    MariageSacrement: 'MariageSacrement',
    Societaire: 'Societaire',
    PremierAspect: 'PremierAspect',
    DeuxiemeAspect: 'DeuxiemeAspect',
    Ecs: 'ECS',
    Ecclesia: 'Ecclesia',
    Graal: 'Graal',
    TeteDor: 'TeteDor',
    SixiemeAspect: 'SixiemeAspect',
    Codicile: 'Codicile',
    Demission: 'Demission',
    Deces: 'Deces'
} as const;
export type TimelineMembreTypes = typeof TimelineMembreTypes[keyof typeof TimelineMembreTypes];

