/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TypesActivitees = {
    ServiceTempleInteresse: 'ServiceTempleInteresse',
    ServiceApprofondissement: 'ServiceApprofondissement',
    WeekEndVille: 'WeekEndVille',
    ConferenceRenouvellement: 'ConferenceRenouvellement',
    ConferenceEcs: 'ConferenceECS',
    ConferenceEcc: 'ConferenceECC',
    ConferenceEcsEcc: 'ConferenceECS_ECC',
    ConventGraalCto: 'ConventGraalCTO'
} as const;
export type TypesActivitees = typeof TypesActivitees[keyof typeof TypesActivitees];

