/**
 * Helios API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypesActivitees } from './typesActivitees';


export interface TypeActiviteDTO { 
    id: number;
    description: string | null;
    code: TypesActivitees;
}
export namespace TypeActiviteDTO {
}


