name: Deploy Intranet
# Trigger on push to the default branch or on pull requests to the default branch
on:
  push:
    paths:
      - 'intranet/**'
      - '.github/workflows/intranet-ci.yml'
    branches:
      - main
      - develop
      - 'release/**'
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write
jobs:
  get-env:
    runs-on: self-hosted
    outputs:
      env: ${{ steps.env.outputs.env }}
      short_env: ${{ steps.env.outputs.short_env }}
    steps:
      - uses: actions/checkout@v4
      - name: Get environment from branch
        id: env
        uses: ./.github/actions/set-env-from-branch

      - name: Show environment
        run: echo "Environment is ${{ steps.env.outputs.env }}"
  build:
    if:  github.ref == 'refs/heads/develop' 
    needs: get-env
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Read package.json
        id: package-version
        uses: jaywcjlove/github-action-package@main
        with:
          path: intranet/package.json

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push intranet image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: intranet
          push: true
          tags: |
            ghcr.io/almyfad/intranet:${{ steps.package-version.outputs.version }}
            ghcr.io/almyfad/intranet:latest
  deploy:
    needs: get-env
    runs-on: self-hosted
    environment: ${{ needs.get-env.outputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read package.json
        id: package-version
        uses: jaywcjlove/github-action-package@main
        with:
          path: intranet/package.json
      - name: Docker compose copy
        run: |
          mkdir -p $HOME/intranet/${{ needs.get-env.outputs.short_env }}
          docker compose -f intranet/docker-compose.yml -f intranet/docker-compose.${{ needs.get-env.outputs.short_env }}.yml config > $HOME/intranet/${{ needs.get-env.outputs.short_env }}/docker-compose.yml
          cd $HOME/intranet/${{ needs.get-env.outputs.short_env }}
          sed -i "s|name: intranet|name: ${{ needs.get-env.outputs.short_env }}|" docker-compose.yml
          sed -i "s|image:.*intranet:.*|image: ghcr.io/almyfad/intranet:${{ steps.package-version.outputs.version }}|" docker-compose.yml
          sed -i "s|API_URL:.*|API_URL: ${{ vars.HELIOS_URL }}|" docker-compose.yml
          sed -i "s|traefik.http.routers.intranet\(.*\)|traefik.http.routers.intranet${{ needs.get-env.outputs.short_env }}\1|" docker-compose.yml
          sed -i "s|traefik.http.services.intranet\(.*\)|traefik.http.services.intranet${{ needs.get-env.outputs.short_env }}\1|" docker-compose.yml

      - name: Show updated docker-compose.yml file
        run: cat $HOME/intranet/${{ needs.get-env.outputs.short_env }}/docker-compose.yml

      - name: Start ${{ needs.get-env.outputs.short_env }} services
        run: |
          cd $HOME/intranet/${{ needs.get-env.outputs.short_env }}
          docker compose up -d
