name: n8n

on:
  push:
    paths:
      - 'n8n/**'
      - '.github/workflows/n8n-ci.yml'

jobs:
  n8n:
    runs-on: self-hosted
    environment: stage
    steps:
      - name: show env
        run: printenv
      - uses: actions/checkout@v3
