name: Deploy Traefik

on:
  push:
    paths:
      - 'traefik/**'
      - '.github/workflows/traefik-ci.yml'
  workflow_dispatch:
jobs:
  traefik:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: copy traefik folder
        run: cp -r traefik/ $HOME
      - name: Deploy Traefik
        run: cd $HOME/traefik && docker compose up -d
