name: Traefik

on:
  push:
    paths:
      - 'traefik/**'
      - '.github/workflows/traefik-ci.yml'

jobs:
  traefik:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: copy traefik.docker-compose.yml
        run: cp -r traefik/ /home/debian/
      - name: Deploy Traefik
        run: cd /home/debian/traefik && docker compose up -d
